import type {
  DbInventory,
  DbLockedMeal,
  DbRecipe,
  NutritionInfo,
  PantryTemplateItem,
} from '@/types/database'

const BASE_NUTRITION: NutritionInfo = {
  calories: 0,
  protein: 0,
  fat: 0,
  carbs: 0,
  fiber: 0,
  vitamins: {
    a: 0,
    b1: 0,
    b2: 0,
    b6: 0,
    b12: 0,
    c: 0,
    d: 0,
    e: 0,
  },
  minerals: {
    iron: 0,
    calcium: 0,
    zinc: 0,
    magnesium: 0,
    potassium: 0,
    sodium: 0,
  },
}

function nutrition(
  calories: number,
  protein: number,
  fat: number,
  carbs: number,
  fiber: number,
): NutritionInfo {
  return {
    ...BASE_NUTRITION,
    calories,
    protein,
    fat,
    carbs,
    fiber,
  }
}

export const DEMO_RECIPES: DbRecipe[] = [
  {
    id: 'demo-natto-rice',
    name: '納豆ご飯',
    meal_type: 'breakfast',
    cuisine_genre: '和食',
    cooking_method: '生',
    cooking_time_minutes: 5,
    difficulty_level: 1,
    ingredients: [
      { name: 'ご飯', amount: 150, unit: 'g', category: 'その他' },
      { name: '納豆', amount: 40, unit: 'g', category: 'その他' },
      { name: 'ねぎ', amount: 10, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: '納豆をご飯にのせる' }],
    nutrition: nutrition(290, 14, 6, 47, 3.5),
    base_servings: 1,
    image_urls: null,
    tags: ['発酵食品', '簡単', 'タンパク質'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-toast-egg',
    name: 'トースト＋目玉焼き',
    meal_type: 'breakfast',
    cuisine_genre: '洋食',
    cooking_method: '焼く',
    cooking_time_minutes: 10,
    difficulty_level: 1,
    ingredients: [
      { name: '食パン', amount: 60, unit: 'g', category: 'その他' },
      { name: '卵', amount: 60, unit: 'g', category: 'その他' },
      { name: 'レタス', amount: 50, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: 'パンと目玉焼きを用意する' }],
    nutrition: nutrition(310, 14, 13, 35, 2),
    base_servings: 1,
    image_urls: null,
    tags: ['卵', '野菜', '洋風', '時短'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-oatmeal',
    name: 'オートミール粥',
    meal_type: 'breakfast',
    cuisine_genre: '洋食',
    cooking_method: '煮る',
    cooking_time_minutes: 10,
    difficulty_level: 1,
    ingredients: [
      { name: 'オートミール', amount: 40, unit: 'g', category: 'その他' },
      { name: '牛乳', amount: 200, unit: 'ml', category: '乳製品' },
      { name: 'バナナ', amount: 100, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: '牛乳でオートミールを煮る' }],
    nutrition: nutrition(360, 12, 7, 63, 4.5),
    base_servings: 1,
    image_urls: null,
    tags: ['食物繊維', 'カルシウム', '時短'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-karaage',
    name: '鶏の唐揚げ定食',
    meal_type: 'lunch',
    cuisine_genre: '和食',
    cooking_method: '揚げる',
    cooking_time_minutes: 30,
    difficulty_level: 3,
    ingredients: [
      { name: '鶏もも肉', amount: 150, unit: 'g', category: '精肉' },
      { name: 'ご飯', amount: 200, unit: 'g', category: 'その他' },
      { name: 'キャベツ', amount: 80, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: '下味をつけた鶏肉を揚げる' }],
    nutrition: nutrition(620, 34, 22, 73, 1.5),
    base_servings: 1,
    image_urls: null,
    tags: ['鶏肉', '揚げ物', '定食', '人気'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-curry',
    name: 'カレーライス',
    meal_type: 'lunch',
    cuisine_genre: '洋食',
    cooking_method: '煮る',
    cooking_time_minutes: 45,
    difficulty_level: 2,
    ingredients: [
      { name: '鶏もも肉', amount: 120, unit: 'g', category: '精肉' },
      { name: '玉ねぎ', amount: 100, unit: 'g', category: '青果' },
      { name: 'じゃがいも', amount: 80, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: '具材を煮込みカレールーを溶かす' }],
    nutrition: nutrition(660, 28, 18, 95, 4),
    base_servings: 1,
    image_urls: null,
    tags: ['鶏肉', '野菜', '人気', 'ご飯もの'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-mabo',
    name: '麻婆豆腐定食',
    meal_type: 'lunch',
    cuisine_genre: '中華',
    cooking_method: '煮る',
    cooking_time_minutes: 20,
    difficulty_level: 2,
    ingredients: [
      { name: '木綿豆腐', amount: 150, unit: 'g', category: 'その他' },
      { name: '豚ひき肉', amount: 80, unit: 'g', category: '精肉' },
      { name: 'にんにく', amount: 5, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: '豆腐とひき肉を辛味だれで煮る' }],
    nutrition: nutrition(590, 30, 18, 78, 2.5),
    base_servings: 1,
    image_urls: null,
    tags: ['豆腐', '豚肉', '中華', 'スパイシー'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-nikujaga',
    name: '肉じゃが',
    meal_type: 'dinner',
    cuisine_genre: '和食',
    cooking_method: '煮る',
    cooking_time_minutes: 35,
    difficulty_level: 2,
    ingredients: [
      { name: '牛薄切り肉', amount: 120, unit: 'g', category: '精肉' },
      { name: 'じゃがいも', amount: 200, unit: 'g', category: '青果' },
      { name: '玉ねぎ', amount: 100, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: '肉と野菜を甘辛く煮る' }],
    nutrition: nutrition(420, 22, 12, 52, 4),
    base_servings: 1,
    image_urls: null,
    tags: ['牛肉', '煮物', '和食', '定番'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-tomato-chicken',
    name: '鶏のトマト煮込み',
    meal_type: 'dinner',
    cuisine_genre: '洋食',
    cooking_method: '煮る',
    cooking_time_minutes: 40,
    difficulty_level: 2,
    ingredients: [
      { name: '鶏もも肉', amount: 180, unit: 'g', category: '精肉' },
      { name: 'トマト缶', amount: 200, unit: 'g', category: 'その他' },
      { name: '玉ねぎ', amount: 80, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: '鶏肉をトマトソースで煮込む' }],
    nutrition: nutrition(380, 30, 20, 15, 3),
    base_servings: 1,
    image_urls: null,
    tags: ['鶏肉', 'トマト', '洋食', 'ヘルシー'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-saba-miso',
    name: 'さばの味噌煮',
    meal_type: 'dinner',
    cuisine_genre: '和食',
    cooking_method: '煮る',
    cooking_time_minutes: 25,
    difficulty_level: 2,
    ingredients: [
      { name: 'さば', amount: 150, unit: 'g', category: '鮮魚' },
      { name: '味噌', amount: 20, unit: 'g', category: '調味料' },
      { name: '生姜', amount: 10, unit: 'g', category: '青果' },
    ],
    steps: [{ order: 1, description: 'さばを味噌だれで煮る' }],
    nutrition: nutrition(320, 28, 16, 16, 0.5),
    base_servings: 1,
    image_urls: null,
    tags: ['魚', '青魚', 'DHA', 'EPA', 'ビタミンD'],
    created_at: '2026-05-24T00:00:00.000Z',
  },
]

export const DEMO_LOCKED_MEALS: DbLockedMeal[] = [
  {
    id: 'demo-lock-monday-breakfast',
    user_id: 'demo-user',
    day_of_week: 0,
    meal_type: 'breakfast',
    recipe_id: 'demo-natto-rice',
    is_eating_out: false,
    note: '平日の朝は固定',
  },
  {
    id: 'demo-lock-wednesday-lunch',
    user_id: 'demo-user',
    day_of_week: 2,
    meal_type: 'lunch',
    recipe_id: null,
    is_eating_out: true,
    note: '水曜昼は外食',
  },
  {
    id: 'demo-lock-friday-dinner',
    user_id: 'demo-user',
    day_of_week: 4,
    meal_type: 'dinner',
    recipe_id: 'demo-saba-miso',
    is_eating_out: false,
    note: '魚の日',
  },
]

export const DEMO_INVENTORY: DbInventory[] = [
  {
    id: 'demo-inventory-rice',
    user_id: 'demo-user',
    ingredient_name: 'ご飯',
    amount: 500,
    unit: 'g',
    expiry_date: '2026-05-27',
    added_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-inventory-onion',
    user_id: 'demo-user',
    ingredient_name: '玉ねぎ',
    amount: 160,
    unit: 'g',
    expiry_date: '2026-05-30',
    added_at: '2026-05-24T00:00:00.000Z',
  },
  {
    id: 'demo-inventory-chicken',
    user_id: 'demo-user',
    ingredient_name: '鶏もも肉',
    amount: 180,
    unit: 'g',
    expiry_date: '2026-05-25',
    added_at: '2026-05-24T00:00:00.000Z',
  },
]

export const DEMO_PANTRY_ITEMS: PantryTemplateItem[] = [
  { name: '味噌', category: '調味料', default_amount: null, unit: null },
  { name: '生姜', category: '青果', default_amount: null, unit: null },
  { name: 'にんにく', category: '青果', default_amount: null, unit: null },
]

export const DEMO_WEEK_START_DATE = '2026-05-18'
export const DEMO_NOW = new Date('2026-05-18T08:00:00+09:00')
export const DEMO_TARGET_CALORIES = 1800
export const DEMO_TARGET_PFC = { protein: 22, fat: 25, carbs: 53 }
