-- Generated by scripts/generate-recipe-image-sql.mjs
-- Review before running in Supabase SQL Editor.
-- Rows with status = 'missing' did not match a recipe in public.recipes.

with image_map(name, image_urls) as (
  values
  ('納豆ご飯', array['https://commons.wikimedia.org/wiki/Special:FilePath/Natto_on_rice.jpg?width=1200']),
  ('卵かけご飯', array['https://commons.wikimedia.org/wiki/Special:FilePath/Tamagokake-gohan_001.jpg?width=1200']),
  ('トースト＋目玉焼き＋サラダ', array['https://commons.wikimedia.org/wiki/Special:FilePath/Fancy_Toast_%28Unsplash%29.jpg?width=1200']),
  ('オートミール粥', array['https://commons.wikimedia.org/wiki/Special:FilePath/Oatmeal_porridge_with_fruits_4.jpg?width=1200']),
  ('味噌汁＋焼き鮭＋ご飯', array['https://commons.wikimedia.org/wiki/Special:FilePath/Breakfast_of_grilled_salmon%2C_miso_soup_and_rice_by_jetalone.jpg?width=1200']),
  ('ヨーグルトパフェ', array['https://commons.wikimedia.org/wiki/Special:FilePath/Yogurt_parfait_with_granola_and_blueberries_in_shot_glasses_with_silverware_spoons_%2817098581522%29.jpg?width=1200']),
  ('フレンチトースト', array['https://commons.wikimedia.org/wiki/Special:FilePath/00_French_Toast.jpg?width=1200']),
  ('豆腐と野菜の炒め定食', array['https://commons.wikimedia.org/wiki/Special:FilePath/Crispy_Tofu_-_Stir_Fry_by_CK_2025-04-06.jpg?width=1200']),
  ('鶏の唐揚げ定食', array['https://commons.wikimedia.org/wiki/Special:FilePath/Karaage-teishoku_of_Yoshinoya.jpg?width=1200']),
  ('豚肉と野菜の生姜焼き定食', array['https://commons.wikimedia.org/wiki/Special:FilePath/Shogayaki_002.jpg?width=1200']),
  ('鮭のムニエル定食', array['https://commons.wikimedia.org/wiki/Special:FilePath/Sole_meuniere_%284689490702%29.jpg?width=1200']),
  ('豚汁定食', array['https://commons.wikimedia.org/wiki/Special:FilePath/Butajiru_by_kina3.jpg?width=1200']),
  ('冷やし中華', array['https://commons.wikimedia.org/wiki/Special:FilePath/Hiyashi_chuka_by_k14.jpg?width=1200']),
  ('カレーライス', array['https://commons.wikimedia.org/wiki/Special:FilePath/Beef_curry_rice_003.jpg?width=1200']),
  ('パスタ ナポリタン', array['https://commons.wikimedia.org/wiki/Special:FilePath/Spaghetti_alle_vongole_napolitano.JPG?width=1200']),
  ('蒸し鶏の冷やしうどん', array['https://commons.wikimedia.org/wiki/Special:FilePath/Cold_Udon_with_Plum_and_Seaweed_at_Muguinb%C5%8D%2C_Shinagawa_Kitchen_%2820230801172642%29.jpg?width=1200']),
  ('麻婆豆腐定食', array['https://commons.wikimedia.org/wiki/Special:FilePath/Mapo_tofu.JPG?width=1200']),
  ('肉じゃが', array['https://commons.wikimedia.org/wiki/Special:FilePath/Nikujaga_by_Takeshi_aka_Momotaro.jpg?width=1200']),
  ('ハンバーグ（デミグラスソース）', array['https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg-Steak.jpg?width=1200']),
  ('白身魚の煮付け', array['https://commons.wikimedia.org/wiki/Special:FilePath/Kinmedai_Nizakana.JPG?width=1200']),
  ('豚の角煮', array['https://commons.wikimedia.org/wiki/Special:FilePath/Kakuni_by_Kanko.jpg?width=1200']),
  ('鶏のトマト煮込み', array['https://commons.wikimedia.org/wiki/Special:FilePath/Chicken_stew_with_mixed_vegetables.jpg?width=1200']),
  ('さばの味噌煮', array['https://commons.wikimedia.org/wiki/Special:FilePath/Miso_Saba.jpg?width=1200']),
  ('野菜たっぷり豚汁＋焼き魚', array['https://commons.wikimedia.org/wiki/Special:FilePath/Breakfast_of_grilled_salmon%2C_miso_soup_and_rice_by_jetalone.jpg?width=1200']),
  ('ペペロンチーノ', array['https://commons.wikimedia.org/wiki/Special:FilePath/Peperoncino.jpg?width=1200']),
  ('親子丼', array['https://commons.wikimedia.org/wiki/Special:FilePath/Oyakodon_003.jpg?width=1200']),
  ('牛丼', array['https://commons.wikimedia.org/wiki/Special:FilePath/Gyudon-withegg-top.jpg?width=1200']),
  ('ぶり大根', array['https://commons.wikimedia.org/wiki/Special:FilePath/Buri-daikon_002.jpg?width=1200']),
  ('えびチリ', array['https://commons.wikimedia.org/wiki/Special:FilePath/Ebi_chili.jpg?width=1200']),
  ('バンバンジー（棒棒鶏）', array['https://commons.wikimedia.org/wiki/Special:FilePath/Bon_bon_chicken_1.jpg?width=1200']),
  ('ガパオライス', array['https://commons.wikimedia.org/wiki/Special:FilePath/Kao_Rad_Pad_Kra-pao_-_Unithai_2023-07-08.jpg?width=1200']),
  ('ロールキャベツ（コンソメ煮）', array['https://commons.wikimedia.org/wiki/Special:FilePath/Stuffed_Cabbage_Golomki.jpg?width=1200']),
  ('鶏とごろごろ野菜のクリームシチュー', array['https://commons.wikimedia.org/wiki/Special:FilePath/Cream_Stew_001.jpg?width=1200']),
  ('サラダチキンのコブサラダ', array['https://commons.wikimedia.org/wiki/Special:FilePath/Cobb_salad_with_chicken%2C_avocado%2C_etc_-_San_Francisco%2C_CA.jpg?width=1200']),
  ('鶏とナスのグリーンカレー', array['https://commons.wikimedia.org/wiki/Special:FilePath/Thai_Green_Curry_with_Rice.jpg?width=1200'])
),
updated as (
  update public.recipes r
  set image_urls = image_map.image_urls
  from image_map
  where r.name = image_map.name
  returning r.name, r.image_urls
)
select
  image_map.name,
  case when updated.name is null then 'missing' else 'updated' end as status,
  updated.image_urls
from image_map
left join updated on updated.name = image_map.name
order by image_map.name;
